const { DB_USERNAME, DB_PASSWORD, DB_DATABASE, DB_HOSTNAME } = process.env;

module.exports = {
    development: {
        migrationStorageTableName: "_sequelize_migrations",
        username: DB_USERNAME,
        password: DB_PASSWORD,
        database: DB_DATABASE,
        host: DB_HOSTNAME,
        dialect: "mysql",
        define: {
            charset: "utf8",
            collate: "utf8_general_ci",
            timestamps: true,
            underscoredAll: true,
            underscored: true,
        },
        multipleStatements: false,
        logging: false,
        pool: {
            cpuUsage: "max",
            max: 30,
            min: 0,
            acquire: 600000,
            idle: 10000,
        },
    },
    test: {
        migrationStorageTableName: "_sequelize_migrations",
        username: DB_USERNAME,
        password: DB_PASSWORD,
        database: DB_DATABASE,
        host: DB_HOSTNAME,
        operatorsAliases: false,
        dialect: "mysql",
        define: {
            charset: "utf8",
            collate: "utf8_general_ci",
            timestamps: true,
            underscoredAll: true,
            underscored: true,
        },
        multipleStatements: false,
        logging: false,
        pool: {
            cpuUsage: "max",
            max: 30,
            min: 0,
            acquire: 600000,
            idle: 10000,
        },
    },
    production: {
        migrationStorageTableName: "_sequelize_migrations",
        username: DB_USERNAME,
        password: DB_PASSWORD,
        database: DB_DATABASE,
        host: DB_HOSTNAME,
        operatorsAliases: false,
        dialect: "mysql",
        define: {
            charset: "utf8",
            collate: "utf8_general_ci",
            timestamps: true,
            underscoredAll: true,
            underscored: true,
        },
        multipleStatements: false,
        logging: false,
        pool: {
            cpuUsage: "max",
            max: 30,
            min: 0,
            acquire: 600000,
            idle: 10000,
        },
    },
};
